const arr_posts = [{
    subject: 'Mat',
    title: 'Funkcja kwadratowa, miejsca zerowe',
    postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
    comments: ['dsaagsdgaga', 'dafhnWUIEGN'],
},
{
  subject: 'Pol',
  title: 'Lalka, streszczenie',
  postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
  comments: [],
},
{
    subject: 'His',
    title: 'Bitwa pod Grunwaldem',
    postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
    comments: ['dsaagsdgaga', 'dafhnWUIEGN'],
},
{
    subject: 'Fiz',
    title: 'Zadanie z kinematyki',
    postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
    comments: ['dsaagsdgaga', 'dafhnWUIEGN'],
},
{
  subject: 'Chem',
  title: 'Reakcja spalania',
  postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
  comments: ['dsaagsdgaga', 'dafhnWUIEGN'],
},
{
  subject: 'Geo',
  title: 'Rzeki europy',
  postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
  comments: ['dsaagsdgaga', 'dafhnWUIEGN'],
},
{
  subject: 'Bio',
  title: 'Komórka grzybowa',
  postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
  comments: ['dsaagsdgaga', 'dafhnWUIEGN'],
},
{
  subject: 'Ang',
  title: 'Czas przeszły czasowniki',
  postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
  comments: ['dsaagsdgaga', 'dafhnWUIEGN'],
},
{
  subject: 'Inne',
  title: 'Niemiecki, odmiany czasowników',
  postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
  comments: ['dsaagsdgaga', 'dafhnWUIEGN'],
},
{
    subject: 'Mat',
    title: 'Funkcja kwadratowa, miejsca zerowe',
    postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
    comments: ['dsaagsdgaga', 'dafhnWUIEGN'],
},
{
  subject: 'Pol',
  title: 'Lalka, streszczenie',
  postText: 'Moglby ktos podeslac jakies najkrotsze streszczenie Lalki? Mam jutro sprawdzian i szybko potrzeboje nauczyc sie czegokolwiek z tej ksiazki',
  comments: ['ma youtube jest szybko audiobook ze streszczeniem, znajdziesz napewno', 'ja mam streszczenie na koncu ksiazki, sprawdz moze tez masz'],
},
{
    subject: 'His',
    title: 'Bitwa pod Grunwaldem',
    postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
    comments: ['dsaagsdgaga', 'dafhnWUIEGN'],
},
{
    subject: 'Fiz',
    title: 'Zadanie z kinematyki',
    postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
    comments: ['dsaagsdgaga', 'dafhnWUIEGN'],
},
{
  subject: 'Chem',
  title: 'Reakcja spalania',
  postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
  comments: ['dsaagsdgaga', 'dafhnWUIEGN'],
},
{
  subject: 'Geo',
  title: 'Rzeki europy',
  postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
  comments: ['dsaagsdgaga', 'dafhnWUIEGN'],
},
{
  subject: 'Bio',
  title: 'Komórka grzybowa',
  postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
  comments: ['dsaagsdgaga', 'dafhnWUIEGN'],
},
{
  subject: 'Ang',
  title: 'Czas przeszły czasowniki',
  postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
  comments: ['dsaagsdgaga', 'dafhnWUIEGN'],
},
{
  subject: 'Inne',
  title: 'Niemiecki, odmiany czasowników',
  postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
  comments: ['dsaagsdgaga', 'Siema'],
},
{
  subject: 'Inne',
  title: 'tibia- wideorecenzja',
  postText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae purus mollis, lacinia erat non, consequat ipsum. Nam et laoreet est. Nulla luctus congue ante, eu ornare urna tempor vitae. Quisque quis odio mi. Vestibulum eleifend euismod nunc ultrices imperdiet. Praesent urna sapien, lobortis pretium malesuada feugiat, ultrices sed arcu. Sed sit amet ornare leo. Cras in luctus velit. Morbi ut lorem dolor. Vivamus interdum tempus arcu at facilisis. Suspendisse ac gravida diam. Donec commodo mollis efficitur. Vivamus vitae dolor rhoncus, posuere ipsum et, scelerisque ipsum. Suspendisse malesuada purus tempor volutpat mattis. Vestibulum sed nisi eros.',
  comments: ['dsaagsdgaga', 'Siema'],
},];

export default arr_posts;
